name: Build Resume
on:
  push:
    tags:
      - "*-*-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ
      
      - name: Rename
        run: mv main.pdf resume.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: resume.pdf